// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelTrace():Promise<void>;

export function GetTraceStatus():Promise<boolean>;

export function StartTrace(arg1:string):Promise<string>;
