// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelTrace() {
  return window['go']['main']['App']['CancelTrace']();
}

export function GetSubmarineCables() {
  return window['go']['main']['App']['GetSubmarineCables']();
}

export function GetTraceStatus() {
  return window['go']['main']['App']['GetTraceStatus']();
}

export function StartTrace(arg1) {
  return window['go']['main']['App']['StartTrace'](arg1);
}
