// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {cables} from '../models';

export function CancelTrace():Promise<void>;

export function GetSubmarineCables():Promise<Array<cables.Cable>>;

export function GetTraceStatus():Promise<boolean>;

export function StartTrace(arg1:string):Promise<string>;
